version: '3'
services:  
  web:    
    build: 
      context: ./
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
        - redis
        - postgres
        - clever_db
    restart: on-failure
    command: > 
      bash -c "export FLASK_APP=traceability
      && export FLASK_ENV=development                
      && flask db upgrade
      && python traceability.py"

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-
        postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      # PGDATA: /data/postgres
      PGDATA: /postgres/data
    volumes:
      # - postgres:/data/postgres
      - postgres:/home/postgresql/data
      # - postgres:/home/postgresql/data
      
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   volumes:
  #      - pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped
  
  clever_db:
    build: 
      context: ./
      dockerfile: ./docker/clever_db/Dockerfile    
    ports:
      - 1401:1433    
    environment:      
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${CLEVER_DB_SA_PASSWORD}
      MSSQL_DB: ${CLEVER_DB_MSSQL_DB}
      MSSQL_USER: ${CLEVER_DB_MSSQL_USER}
      MSSQL_PASSWORD: ${CLEVER_DB_MSSQL_PASSWORD}
    volumes:      
      - /home/mssql/clever_data:/var/opt/mssql
      # - /var/lib/clever_data:/var/opt/mssql
    container_name: clever_db
  
  redis:
    image: redis




networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    # pgadmin:
      
  
  
  
  
  