"""empty message

Revision ID: 016f797c7ad9
Revises: da7b277b020a
Create Date: 2021-06-01 12:50:27.412271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016f797c7ad9'
down_revision = 'da7b277b020a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xml_dataP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xml_data', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(),  nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xml_dataP')
    # ### end Alembic commands ###


def upgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

