"""empty message

Revision ID: 5dfc78fbc9d7
Revises: 6a2f7bed6607
Create Date: 2020-12-15 15:39:32.975238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfc78fbc9d7'
down_revision = '6a2f7bed6607'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lot', 'manufacturer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lot', 'manufacturer_lot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lot', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lot', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lot', 'manufacturer_lot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lot', 'manufacturer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def upgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

