"""empty message

Revision ID: 6a2f7bed6607
Revises: 
Create Date: 2020-12-15 14:33:38.599207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '6a2f7bed6607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xml_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xml_data', mssql.XML(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('error', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('empty_doc', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('unsupported_doc', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xml_data')
    # ### end Alembic commands ###

