"""empty message

Revision ID: b08fb31c554b
Revises: 6bd11bf2a95c
Create Date: 2021-06-03 21:29:28.708558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b08fb31c554b'
down_revision = '6bd11bf2a95c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xml_dataP', sa.Column('empty_doc', sa.Boolean(), nullable=True))
    op.add_column('xml_dataP', sa.Column('unsupported_doc', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xml_dataP', 'unsupported_doc')
    op.drop_column('xml_dataP', 'empty_doc')
    # ### end Alembic commands ###


def upgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('XMLData', 'xml_data',
               existing_type=mssql.XML(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('XMLData', 'xml_data',
               existing_type=mssql.XML(),
               nullable=False)
    # ### end Alembic commands ###

